name = "task-manager-api"
main = "src/index.ts"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "task-manager-db"
database_id = "3bc696d2-224c-4a46-a8ec-7a3cec5d2086"
migrations_dir = "drizzle/migrations"

